experience_levels = ["Junior", "Middle", "Senior"]
possible_technologies = [
    "pyglet",
    "seaborn",
    "sqlalchemy",
    "gcp",
    "email_validator",
    "tox",
    "fastapi",
    "numpy",
    "bash",
    "pymongo",
    "pyjwt",
    "flask-restful",
    "typer",
    "peewee",
    "pyodbc",
    "saltstack",
    "dash",
    "plotly",
    "keras",
    "cryptography",
    "kivy",
    "behave",
    "cx_Freeze",
    "pillow",
    "matplotlib",
    "httpx",
    "unittest",
    "rabbitmq",
    "threads",
    "hive",
    "docker",
    "mongoengine",
    "tensorflow",
    "django",
    "factory_boy",
    "scikit-learn",
    "postgresql",
    "webgrafana",
    "mypy",
    "oauthlib",
    "elk",
    "faker",
    "arcade",
    "databases",
    "kibana",
    "cx_Oracle",
    "github",
    "apache",
    "opencv",
    "mongodb",
    "jenkins",
    "beautifulsoup4",
    "lightgbm",
    "fast-api",
    "splinter",
    "pyenv",
    "pandas",
    "asyncio",
    "celery",
    "fast api",
    "tkinter",
    "connexion",
    "py2exe",
    "rich",
    "mysql",
    "pipenv",
    "power bi",
    "flask",
    "scrapy",
    "fire",
    "hadoop",
    "alembic",
    "gitlab",
    "pyinstaller",
    "nose",
    "redis",
    "catboost",
    "pusher",
    "beautiful soup",
    "pyqt",
    "pywebview",
    "ipywidgets",
    "bokeh",
    "pygame",
    "drf",
    "kubernetes",
    "multithreading",
    "multiprocessing",
    "metabase",
    "pytest",
    "pyqtdeploy",
    "nbconvert",
    "socket.io",
    "kafka",
    "requests",
    "flask-socketio",
    "flake8",
    "prometheus",
    "prompt_toolkit",
    "azure",
    "rq",
    "ansible",
    "graphql",
    "bottle",
    "scipy",
    "supervisord",
    "uwsgi",
    "airflow",
    "selenium",
    "fabric",
    "memcached",
    "aws",
    "marshmallow",
    "pylint",
    "httpie",
    "ipython",
    "superset",
    "auto-py-to-exe",
    "django rest framework",
    "git",
    "pydantic",
    "aiohttp",
    "pyside",
    "cucumber",
    "terraform",
    "pyramid",
    "jupyter",
    "django-oracle-database-backend",
    "pytorch",
    "sql",
    "tornado",
    "virtualenv",
    "web2py",
    "streamlit",
    "gunicorn",
    "travis",
    "django-rest-framework",
    "tableau",
    "spark",
    "logstash",
    "xgboost",
    "wxpython",
    "nginx",
    "validators",
    "linux",
]

# possible_technologies = [
#     "web" "grafana",
#     "metabase",
#     "pytest",
#     "scipy",
#     "scrapy",
#     "rabbitmq",
#     "github",
#     "hadoop",
#     "jupyter",
#     "gunicorn",
#     "unittest",
#     "keras",
#     "drf",
#     "airflow",
#     "supervisord",
#     "tkinter",
#     "ipywidgets",
#     "tableau",
#     "pyside",
#     "splinter",
#     "bokeh",
#     "mongodb",
#     "sqlalchemy",
#     "power bi",
#     "fast api",
#     "uwsgi",
#     "streamlit",
#     "gcp",
#     "ipython",
#     "asyncio",
#     "sql",
#     "kibana",
#     "flask",
#     "linux",
#     "opencv",
#     "terraform",
#     "pytorch",
#     "plotly",
#     "hive",
#     "postgresql",
#     "django rest framework",
#     "matplotlib",
#     "apache",
#     "django",
#     "elk",
#     "travis",
#     "ansible",
#     "fast-api",
#     "dash",
#     "aiohttp",
#     "redis",
#     "bash",
#     "superset",
#     "pandas",
#     "kafka",
#     "spark",
#     "numpy",
#     "docker",
#     "seaborn",
#     "selenium",
#     "nginx",
#     "prometheus",
#     "mysql",
#     "threads",
#     "multithreading",
#     "multiprocessing",
#     "tensorflow",
#     "aws",
#     "beautiful soup",
#     "alembic",
#     "pyqt",
#     "fastapi",
#     "requests",
#     "azure",
#     "gitlab",
#     "kubernetes",
#     "jenkins",
#     "logstash",
#     "git",
#     "celery",
#     "scikit-learn",
# ]
